title: Almazis' Den
author:
  name: Anna Vasenina
  email: almazisdev@gmail.com
description: Collection of public documents

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/Almazis"
    - title: Telegram
      icon: telegram
      url: "https://t.me/Almazis"
  hide_site_feed_link: true
